require 'prawn'

class ChannelHookupPdf < Prawn::Document
  def initialize(instruments, show)
    super(top_margin: 70)
    @instruments = instruments.sort_by { |a| [a.channel ? 0 : 1, a.channel] }
    @show = show

    header
    channel_hookup
    footer
  end

  def header
    fill_color "A67C00"
    text @show.name + " Channel Hookup"
  end

  def channel_hookup
    fill_color "000000"
    data = [[
      "Chan",
      "Univ",
      "Addr",
      "Fixture",
      "Purpose",
      "Position",
      "Unit",
      "Ckt Name",
      "Ckt#"
    ]]

    @instruments.each do |instrument|
      if instrument.unit_number && instrument.unit_number * 10 % 10 == 0
        unit_number = instrument.unit_number.floor
      else
        unit_number = instrument.unit_number
      end
      data += [[
        instrument.channel,
        instrument.universe,
        instrument.address,
        instrument.fixture.name,
        instrument.purpose,
        instrument.position,
        unit_number,
        instrument.circuit_name,
        instrument.circuit_number
      ]]
    end
    table(
      data,
      :header => true,
      :cell_style => { :borders => [:bottom] }
    )
  end

  def footer
    fill_color "A67C00"
    move_cursor_to 20
    text "Generated by RUNLIGHTS (pre-alpha)"
  end
end
