require 'prawn'

class InstrumentSchedulePdf < Prawn::Document
  def initialize(instruments, show)
    super(top_margin: 70)
    @instruments = instruments.sort_by { |a| [a.position.nil? ? 1 : 0, a.position.blank? ? 1 : 0, a.position, a.unit_number ? 1 : 0, a.unit_number] }
    @show = show

    header
    instrument_schedule
    footer
  end

  def header
    text @show.name + " Instrument Schedule"
  end

  def instrument_schedule
    data = [[
      "Position",
      "Unit",
      "Fixture",
      "Purpose",
      "Chan",
      "Univ",
      "Addr",
      "Ckt Name",
      "Ckt#"
    ]]

    @instruments.each do |instrument|
      data += [[
        instrument.position,
        instrument.unit_number,
        instrument.fixture.name,
        instrument.purpose,
        instrument.channel,
        instrument.universe,
        instrument.address,
        instrument.circuit_name,
        instrument.circuit_number
      ]]
    end
    table(data, :header => true)
  end

  def footer
    move_cursor_to 20
    text "Generated by RUNLIGHTS (pre-alpha)"
  end
end
